### ISSUE TITLE
Remove duplicated kernel

### ISSUE THREAD

**Issue by simo1427** [simo1427/HaraliCL#1]
## Current situation
As of now, there are two kernels - one for extracting features with a symmetric matrix, the other for doing so with an asymmetric matrix. 

## To-do:

- [x] Remove the duplicated kernel
- [x] Add OpenCL preprocessor directives
- [ ] Improve documentation
- [x] Investigate possible removal of `pair`
